INSERT INTO mst_request_type_params(request_id,request_param_name,request_param_data_type,airline_code,created_by,updated_by,updated_on,col_size,control_type,TABLE_COL_NAME)VALUES(3,'Module','String','EK','Neeraj','Neeraj',sysdate(),10,'text','MODULE');
INSERT INTO mst_request_type_params(request_id,request_param_name,request_param_data_type,airline_code,created_by,updated_by,updated_on,col_size,control_type,TABLE_COL_NAME)VALUES(3,'Screen code' ,'String','EK','Neeraj','Neeraj',sysdate(),15,'text','SCR_CODE');
INSERT INTO mst_request_type_params(request_id,request_param_name,request_param_data_type,airline_code,created_by,updated_by,updated_on,col_size,control_type,TABLE_COL_NAME)VALUES(3,'Menu','String','EK','Neeraj','Neeraj',sysdate(),25,'text','MENU');
INSERT INTO mst_request_type_params(request_id,request_param_name,request_param_data_type,airline_code,created_by,updated_by,updated_on,col_size,control_type,TABLE_COL_NAME)VALUES(3,'Jira Id','String','EK','Neeraj','Neeraj',sysdate(),10,'text','JIRA_ID');
INSERT INTO mst_request_type_params(request_id,request_param_name,request_param_data_type,airline_code,created_by,updated_by,updated_on,col_size,control_type,TABLE_COL_NAME)VALUES(3,'SUC','String','EK','Neeraj','Neeraj',sysdate(),10,'text','SUC');
INSERT INTO mst_request_type_params(request_id,request_param_name,request_param_data_type,airline_code,created_by,updated_by,updated_on,col_size,control_type,TABLE_COL_NAME)VALUES(3,'Developer','String','EK','Neeraj','Neeraj',sysdate(),20,'text','DEVELOPER');
INSERT INTO mst_request_type_params(request_id,request_param_name,request_param_data_type,airline_code,created_by,updated_by,updated_on,col_size,control_type,TABLE_COL_NAME)VALUES(3,'Block Name','String','EK','Neeraj','Neeraj',sysdate(),25,'text','BLOCK_NAME');
INSERT INTO mst_request_type_params(request_id,request_param_name,request_param_data_type,airline_code,created_by,updated_by,updated_on,col_size,control_type,TABLE_COL_NAME)VALUES(3,'Descriptions','String','EK','Neeraj','Neeraj',sysdate(),25,'textarea','DESCRIPTION');
INSERT INTO mst_request_type_params(request_id,request_param_name,request_param_data_type,airline_code,created_by,updated_by,updated_on,col_size,control_type,TABLE_COL_NAME)VALUES(3,'Airline Code','String','EK','Neeraj','Neeraj',sysdate(),3,'text','AIRLINECODE');
